### ISSUE TITLE
Table with PolyRatFun breaks using tform

### ISSUE THREAD

**Issue by apelloni** [benruijl/forcer#2]
I stumble upon an interesting bug while using tFORM when running the following code:

```python
test.frm
__________________________________________________________
#--
table sparse rtop(2);
table sparse top(1);
table sparse c(2);
Auto S x;
S w,d;
CF rat,cc;

PolyRatFun rat;

* Include Transformations 
Fill rtop(1,1) = + cc(1,1)*top(2) 
                 + cc(1,2)*top(3) 
                 + cc(1,3)*top(4);
Fill rtop(2,4) = + cc(2,1)*top(3);
Fill rtop(2,2) = + cc(2,2)*top(5);
Fill rtop(3,6) = top(7);
Fill rtop(3,3) = top(5);

* Include Coefficients 
Fill c(1,1) = rat((-2*d^3+14*d^2-32*d+24),(6*d^3-69*d^2+264*d-336));
Fill c(1,2) = rat(((50*d^4-550*d^3+2248*d^2-4040*d+2688)*w-40*d^4+452*d^3-1892*d^2+3472*d-2352),
                            ((18*d^4-267*d^3+1482*d^2-3648*d+3360)*w-18*d^4+267*d^3-1482*d^2+3648*d-3360));
Fill c(1,3) = rat(((2*d^3-14*d^2+32*d-24)*w),((18*d^3-195*d^2+702*d-840)*w-18*d^3+195*d^2-702*d+840));
Fill c(2,1) = rat((-5*d+14),((d-4)*w));
Fill c(2,2) = rat((5*d-14),(3*d-10));

L F = top(1);

#do i=1,3
    id top(?a) = rtop(`i',?a);
    id cc(?a) = c(?a);
    id rtop(x1?,x2?) = top(x2);
    .sort
#enddo
print +s;
.end
```
The code is the minimal case I managed to extract from some reduction tables that I'm applying using FORM.

When running the code with `form` everything works as expected and the result is:
```
> form test.frm
F = + top(5)*rat(20*d^3 - 156*d^2 + 400*d - 336,9*d^3 - 102*d^2 + 384*d - 480);
 ```
 Things go very wrong (on some runs) when trying to use `tform`
 ```
> tform -w2 test.frm
F = + top(5)*rat(4928*d^4,20160*d^4);
 ```
 
 
 I don't know if this problem is related to the following but it may be. 
 When postponing the call for `PolyRatFun rat;` till after the `#do` loop, I get that whenever the two outputs coincide they are still represented in different ways
 ```diff
 <        + top(5)*rat(20*d^3 - 156*d^2 + 400*d - 336,9*d^3 - 102*d^2 + 384*d - 
<       480)
---
>        + top(5)*rat( - 336 + 400*d - 156*d^2 + 20*d^3, - 480 + 384*d - 102*d^2
>        + 9*d^3)
```
with the first one obtained using `form` and the second with `tform -w2`.

**Comment by jodavies** [comment]
This is resolved for me by using `On highfirst;` at the start of your code.

Maybe this is the first non-trivial instance of https://github.com/vermaseren/form/issues/336#issuecomment-558996395 that anyone has found since the patches that mostly repaired things there?

**Comment by apelloni** [comment]
This seems to be the solution.
I'll try to run the real code with this option, which indeed solved the issue in this case. 

Since I posted it to the wrong github I think I'll delete this issue and resubmit it (to form github) in case something goes wrong again.
